### ISSUE TITLE
Generation of key word indexes

### ISSUE THREAD

**Issue by elfring** [ransford/pdflatex-makefile#32]
How would you like to integrate commands for [the generation of indexes from marked key words](https://en.wikibooks.org/wiki/LaTeX/Indexing)?

**Comment by ransford** [comment]
Similar to how we support glossaries.

First step: edit the `example/example.tex` to generate an index; I believe this will make an `.idx` file.

Second step: add a Makefile rule to generate `.idx` files and correctly incorporate them into the build.

Pull request welcome; otherwise I can get to this eventually (not soon).

**Comment by ransford** [comment]
update: i did not get to this
